[package]
name = "vaughan"
version = "0.1.0"
edition = "2021"
rust-version = "1.76"

[dependencies]
polars = { version = "0.39.2", features = [
  "lazy",
  "test",
  "parquet",
  "ndarray",
  "diff",
  "is_in",
  "serde",
  "log",
  "avx512",
] }
