---
name: General Feature Request
description: Suggest an 
labels: [Enhancement,Algorithm, Needs Triage]

body:
  - type: input
    id: title
    attributes:
      description: What is the algorithm or calculation called?
      label: title
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      description: >
        Please provide a clear and concise description of the feature you're requesting, including name and a description. Please include sources if possible
      label: Enhancement Description
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      description: >
        Please describe a situation in which this feature would be useful to you
      label: Use case
  - type: textarea
    id: citation
    attributes:
      description: >
        Please provide citations where this work is described if possible/applicable
      label: Citations
