---
name: Bug Report
description: Report a bug in Vaughan
labels: [Bug, Needs Triage]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: HydroMT version checks
      options:
        - label: I have checked that this issue has not already been reported.
          required: true
        - label: I have checked that this bug exists on the main branch at time of writing.
          required: true
  - type: textarea
    id: example
    attributes:
      description: >
        Please provide a minimal, copy-pastable example or a link to a public repository that reproduces the behavior your wish to report. 
      label: Minimum Working Example (MWE)
    validations:
      required: true
  - type: textarea
    id: current-behaviour
    attributes:
      description: >
        Please provide a description of the incorrect behaviour shown in the reproducible example
      label: Current behaviour
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      description: >
        Please provide a description of what you think the behaviour should be
      label: Desired behaviour
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      description: >
        Please add any other context about the bug here
      label: Additional context
    validations:
      required: false
