---
name: General Feature Request
description: Suggest an feature
labels: [Enhancement, Needs Triage]

body:
  - type: textarea
    id: description
    attributes:
      description: >
        Please provide a clear and concise description of the feature you're requesting
      label: Enhancement Description
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      description: >
        Please describe a situation in which this feature would be useful to you, with code or cli examples if possible
      label: Use case
  - type: textarea
    id: context
    attributes:
      description: >
        Please add any other context such as implementation about the enhancement here if applicable
      label: Additional Context
